swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /estudiante/:
    get:
      tags:
      - estudiante
      description: get Estudiante
      operationId: EstudianteController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Estudiante'
        "403":
          description: ""
    post:
      tags:
      - estudiante
      description: create Estudiante
      operationId: EstudianteController.Post
      parameters:
      - in: body
        name: body
        description: body for Estudiante content
        required: true
        schema:
          $ref: '#/definitions/models.Estudiante'
      responses:
        "201":
          description: '{int} models.Estudiante'
        "403":
          description: body is empty
  /estudiante/{id}:
    get:
      tags:
      - estudiante
      description: get Estudiante by id
      operationId: EstudianteController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Estudiante'
        "403":
          description: :id is empty
    put:
      tags:
      - estudiante
      description: update the Estudiante
      operationId: EstudianteController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Estudiante content
        required: true
        schema:
          $ref: '#/definitions/models.Estudiante'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Estudiante'
        "403":
          description: :id is not int
    delete:
      tags:
      - estudiante
      description: delete the Estudiante
      operationId: EstudianteController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /materia/:
    get:
      tags:
      - materia
      description: get Materia
      operationId: MateriaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Materia'
        "403":
          description: ""
    post:
      tags:
      - materia
      description: create Materia
      operationId: MateriaController.Post
      parameters:
      - in: body
        name: body
        description: body for Materia content
        required: true
        schema:
          $ref: '#/definitions/models.Materia'
      responses:
        "201":
          description: '{int} models.Materia'
        "403":
          description: body is empty
  /materia/{id}:
    get:
      tags:
      - materia
      description: get Materia by id
      operationId: MateriaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Materia'
        "403":
          description: :id is empty
    put:
      tags:
      - materia
      description: update the Materia
      operationId: MateriaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Materia content
        required: true
        schema:
          $ref: '#/definitions/models.Materia'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Materia'
        "403":
          description: :id is not int
    delete:
      tags:
      - materia
      description: delete the Materia
      operationId: MateriaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Estudiante:
    title: Estudiante
    type: object
    properties:
      CodEstudiante:
        type: number
        format: double
      Id:
        type: integer
        format: int64
  models.Materia:
    title: Materia
    type: object
    properties:
      CodMateria:
        type: number
        format: double
      Id:
        type: integer
        format: int64
tags:
- name: estudiante
  description: |
    EstudianteController operations for Estudiante
- name: materia
  description: |
    MateriaController operations for Materia
